"""Shared, explicit figure colors for allocation visualizations."""

# Full fixed palette used by the chord charts.
MUTED_ACADEMIC_PALETTE = (
    "#243B53", "#334E68", "#486581", "#627D98", "#829AB1", "#9FB3C8",
    "#245B66", "#346F78", "#4F858C", "#6A9A9B", "#86ADAA", "#A7C5BE",
    "#3F624D", "#55745C", "#6B876C", "#81997B", "#98AA8C", "#B2BEA3",
    "#646B4F", "#777A55", "#8B895D", "#9E9768", "#B0A576", "#C0B58B",
    "#8C6D32", "#A17E3D", "#B58F4A", "#C49E5A", "#D0AD70", "#D9BD8B",
    "#A86F58", "#BA7D64", "#C98C70", "#D59C80", "#DEAD94", "#E6BFA9",
    "#A96562", "#BB7470", "#C9827D", "#D3948E", "#DDA6A1", "#E5B9B4",
    "#8E6874", "#A07883", "#B28992", "#C19AA0", "#CEACB0", "#DBC0C2",
)

# Exact solid outer-sector colors generated by the existing chord-chart node
# mapping. Both chord and stacked-bar scripts import this one dictionary.
CHEMICAL_COLORS = {
    "3HP": "#243B53",
    "ETHANOL": "#A7C5BE",
    "FDCA": "#3F624D",
    "FURFURAL": "#55745C",
    "HMF": "#6B876C",
    "ISOPRENE": "#81997B",
    "LACTIC ACID": "#98AA8C",
    "LEVULINIC ACID": "#B2BEA3",
    "SORBITOL": "#BA7D64",
    "SUCCINIC ACID": "#D59C80",
    "XYLITOL": "#486581",
}
